language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y libsfml-dev
  - unzip ext/tileson-master.zip  -d ext/
  
script:
  - cmake -DENABLE_UNITTESTS=ON -DENABLE_STRESSTEST=ON -DENABLE_DISPLAY_TESTS=OFF .
  - make MyAwesomeGame
  - make StressTest
  - make UnitTests
  - ./UnitTests
