language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      services:
        - xvfb
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y libsfml-dev
  - unzip ext/tileson-master.zip  -d ext/
  - pip install --user cpp-coveralls
  
script:
  - cmake -DENABLE_UNITTESTS=ON -DENABLE_STRESSTESTS=ON -DENABLE_DISPLAY_TESTS=OFF -DENABLE_COVERAGE=ON .
  - make MyAwesomeGame
  - make StressTests
  - make UnitTests
  - ./UnitTests

after_success:
  - coveralls --exclude src/game --exclude src/jamtemplate/sdl --exclude ext --exclude src/stresstests --exclude src/unittests --gcov-options '\-lp'
  
