language: cpp

os: linux
dist: focal
services:
  - xvfb
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-9
env:
  - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y libsfml-dev
  - unzip ext/tileson-master.zip  -d ext/
  - pip install --user cpp-coveralls

script:
  - cmake -DENABLE_UNITTESTS=ON -DENABLE_STRESSTESTS=ON -DENABLE_DISPLAY_TESTS=OFF -DENABLE_COVERAGE=ON .
  - make -j 2
  - ./UnitTests

after_success:
  - coveralls -e src/game -e src/jamtemplate/sdl -e ext -e src/stresstests -e src/unittests -e src/jamtemplate/sfml/keyboard_input_lib.cpp -e src/jamtemplate/sfml/mouse_input_lib.cpp -e src/jamtemplate/sfml/sound.cpp -e src/jamtemplate/sfml/music_player.cpp --gcov-options '\-lp'
  
