name: Test Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildWeb:
    runs-on: ubuntu-latest

    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - uses: mymindstorm/setup-emsdk@v9

      - uses: actions/checkout@v2

      - name: CMake
        run: emcmake cmake -B ${{github.workspace}}/build -DENABLE_STRESSTESTS=ON -DENABLE_DISPLAY_TESTS=OFF -DENABLE_WEB=ON.

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: emmake make
