name: Test Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TestsLinuxSFML:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up system libs
        run: sudo apt-get install -y libsfml-dev jackd

      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 100M

      - name: CMake
        run: |
          cmake \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j 4

      - name: StartJack
        run: jackd -d dummy &

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./jt_tests --gtest_shuffle
          working-directory: ${{github.workspace}}/build/test/unit/jt_test

  TestsLinuxSDL:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up SDL and jack
        run: |
          sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libsdl2-image-dev

      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 100M

      - name: CMake
        run: |
          cmake \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DUSE_SFML=OFF \
          -DENABLE_AUDIO_TESTS=OFF \
          -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j 4

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./jt_tests --gtest_shuffle
          working-directory: ${{github.workspace}}/build/test/unit/jt_test

  TestsWindows:
    runs-on: windows-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - uses: actions/checkout@v2

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DENABLE_AUDIO_TESTS=OFF .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build/test/unit/jt_test
        run: Debug\jt_tests.exe --gtest_shuffle

  BuildWeb:
    runs-on: ubuntu-latest
    env:
      EMCC_CCACHE: 1
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - uses: mymindstorm/setup-emsdk@v9

      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 100M

      - name: CMake
        run: |
          emcmake cmake -B ${{github.workspace}}/build \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DENABLE_DEMOS=ON \
          -DENABLE_UNITTESTS=OFF \
          -DENABLE_WEB=ON \
          -DUSE_SFML=OFF .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: emmake make

  CodeCoverage:
    needs: TestsLinuxSFML
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up system libs
        run: |
          sudo apt-get install -y \
          libsfml-dev \
          jackd

      - name: Set up cpp-coveralls
        run: pip install --user cpp-coveralls

      - uses: actions/checkout@v2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.type }}
          max-size: 100M

      - name: CMake
        run: |
          cmake \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DENABLE_COVERAGE=ON .

      - name: Build
        run: make -j 4

      - name: StartJack
        run: jackd -d dummy &

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./jt_tests
          working-directory: ${{github.workspace}}/test/unit/jt_test

      - name: Coveralls
        working-directory: ${{github.workspace}}
        run: |
          coveralls \
          --verbose \
          -t ${{ secrets.coveralls_token }} \
          -e _deps \
          -e ext \
          -e test \
          -e impl/game \
          -e impl/gamelib \
          -e impl/jamtemplate/sdl \
          -e impl/jamtemplate/sfml/keyboard_input_lib.cpp \
          -e impl/jamtemplate/sfml/mouse_input_lib.cpp \
          --gcov-options '\-lp'
