name: Test Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TestsLinuxSFML:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up system libs
        run: sudo apt-get install -y libsfml-dev jackd

      - uses: actions/checkout@v2

      - name: CMake
        run: cmake -B ${{github.workspace}}/build .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j 4

      - name: StartJack
        run: jackd -d dummy &

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./UnitTests
          working-directory: ${{github.workspace}}/build/src/unittests

  TestsLinuxSDL:
    runs-on: ubuntu-latest
    env:
      SDL_AUDIODRIVER: jack
      AUDIODEV: jack
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up SDL and jack
        run: sudo apt-get install -y  libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev

      - uses: actions/checkout@v2

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DUSE_SFML=OFF -DENABLE_DISPLAY_TESTS=OFF.

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make -j 4

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./UnitTests
          working-directory: ${{github.workspace}}/build/src/unittests

  TestsWindows:
    runs-on: windows-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - uses: actions/checkout@v2

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DENABLE_DISPLAY_TESTS=OFF

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build/src/unittests
        run: Debug\UnitTests.exe

  BuildWeb:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - uses: mymindstorm/setup-emsdk@v9

      - uses: actions/checkout@v2

      - name: CMake
        run: emcmake cmake -B ${{github.workspace}}/build -DENABLE_STRESSTESTS=ON -DENABLE_UNITTESTS=OFF -DENABLE_WEB=ON -DUSE_SFML=OFF .

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: emmake make

  CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Set up system libs
        run: sudo apt-get install -y libsfml-dev jackd

      - name: Set up cpp-coveralls
        run: pip install --user cpp-coveralls

      - uses: actions/checkout@v2

      - name: CMake
        run: |
          cmake \
          -DENABLE_COVERAGE=ON .

      - name: Build
        run: make -j 4

      - name: StartJack
        run: jackd -d dummy &

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./UnitTests
          working-directory: ${{github.workspace}}/src/unittests

      - name: Coveralls
        working-directory: ${{github.workspace}}
        run: |
          coveralls \
          -t ${{ secrets.coveralls_token }} \
          -e _deps \
          -e ext \
          -e src/game \
          -e src/stresstests \
          -e src/unittests \
          -e src/jamtemplate/sdl \
          -e src/jamtemplate/sfml/keyboard_input_lib.cpp \
          -e src/jamtemplate/sfml/mouse_input_lib.cpp \
          --gcov-options '\-m'
