name: Test Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

UnitTestsWindows:
  runs-on: windows-latest

  steps:
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: '3.19.x'

    - uses: actions/checkout@v2

    - name: CMake
      run: cmake -B ${{github.workspace}}/build -DENABLE_STRESSTESTS=ON -DENABLE_DISPLAY_TESTS=OFF

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/build/src/unittests
      run: Debug\UnitTests.exe

